### ISSUE TITLE
Can not mix tags

### ISSUE THREAD

**Issue by ThomasAtome** [tleunen/pixi-multistyle-text#13] opened 2016-12-22 16:57 UTC
Hi,

I just report you a bug or a feature (lol), we can't mix tags.

Example :

```
var textSample = new MultiStyleText("<pixi>Pixi.js <pixiBis>can has</pixi> multiline</pixiBis>"
			{
				default: { fontFamily: "Tahoma", fontSize: "35px", fill: "white" },
				pixi: { fill: "#D90057" },
				pixiBis: { fill: "red" }
			}
		);
```

This will print bad render, it seems that the name tag isn't sensitive, the first closer tag will close the first open tag, even if the name isn't the same ;)

Thanks,

**Comment by bluepichu** [comment] 2016-12-22 17:07
That is true - the way that the nesting feature was written, the assumption was that tag nesting would be HTML-like, and thus each closing tag must match the deepest-nested open tag at that time.  To some extent, this is intended behavior.

If there is interest in making tags match like that, I could certainly try to make that work, but I'm also interested in what the intended behavior would be.  Which properties are inherited by text - those defined on the most-recently-opened tag, or some other metric?

**Comment by ThomasAtome** [comment] 2016-12-23 08:01
Thanks for reply. I think example is better than words, and for us, this is the intended behavior :

`
var textSample = new MultiStyleText("<pixi>Pixi.js <pixiBis>can has</pixi> multiline</pixiBis>"
			{
				default: { fontFamily: "Tahoma", fontSize: "35px", fill: "white" },
				pixi: { fontFamily: "Josephin", fontSize: "20px", fill: "#D90057" },
				pixiBis: { fill: "red" }
			}
		);
`

In this example, "Pixi.js" should have the pixi style, then "can has" should have pixiBis style that overwrite properties of pixi style, so all pixi properties + fill that is overwrote with "red" and then "multiline" should overwrite the default style, so all default style + fill that is overwrote with "red"

**Comment by tleunen** [comment] 2016-12-23 13:55
Ideally, tags shouldn't be mixed like that. 
In your case, I'd write this:
```
<pixi>Pixi.js <pixiBis>can has</pixiBis></pixi><pixiBis> multiline</pixiBis>
```

But I believe there's no inheritance of properties, so `canHas` would only have the props from `pixiBis`. Can you confirm?

**Comment by ThomasAtome** [comment] 2016-12-23 15:43
After some reflections, the best approach is that tags has inheritance, and then we have to create dynamically some tags.

So my old example :

`<pixi>Pixi.js <pixiBis>can has</pixi> multiline</pixiBis>`

Seems to be :

`<pixi>Pixi.js </pixi><pixi+pixiBis>can has<pixi+pixiBis><pixiBis> multiline</pixiBis>`

Where pixi is a style, pixiBis too and pixi+pixiBis is the pixiBis style with inheritance of the pixi style

**Comment by bluepichu** [comment] 2016-12-28 04:34
After some thought, I'm going to close this as being intended behavior.  The feature (as written currently) isn't so much support for _mixing_ tags as it is _nesting_ tags.  The solution that @tleunen mentioned is probably the best one:

```
<pixi>Pixi.js <pixiBis>can has</pixiBis></pixi><pixiBis> multiline</pixiBis>
```

Since inheritance works properly, this should give you what you're looking for.  The alternative is to generate your own "mixed" tags as you have above, but you'd have to do that before passing it on to this library.

Anyway, I'll close this for now, but I'm certainly willing to revisit it if someone provides a suggested specification and a solid use case that isn't easily converted to nesting.

**Closed by bluepichu** 2016-12-28 04:34 UTC
